<?php

namespace AppBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserRole()
    {
        $role = $this->createQueryBuilder('r')
            ->where("r.role = :roleName")
            ->setParameter('roleName', 'ROLE_USER')
            ->getQuery()
            ->getOneOrNullResult();
        
        return $role;
    }

   

}
