<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{

    public function loadUserByUsername($username)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();

        /** @var $user User */
        if ($user instanceof UserInterface) {
            $user->setFlReturnRolesObject(true);
        }

        return $user;
    }

    /**
     * @param $apiKey
     * @return User|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getByApiKey($apiKey)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.apiKey = :api_key')
            ->setParameter('api_key', $apiKey)
            ->getQuery()
            ->getOneOrNullResult();

        return $user;
    }
}
