# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js|pdf|font)/
            security: false

        main:
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                use_referer: true
                default_target_path: homepage
                always_use_default_target_path: false
            remember_me:
                secret: '%secret%'
                path: /
            logout:
                path: signout
                target: homepage

        login_firewall:
            pattern: ^/login$
            anonymous: ~
        secured_area:
            pattern: ^/
            form_login: ~

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role: ROLE_ADMIN }